# Generated by Django 3.2.3 on 2021-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_type',
            field=models.CharField(default='Blog', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
