# Generated by Django 3.2.3 on 2021-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(blank=True, default='No Preview Availible', null=True),
        ),
    ]
