# Generated by Django 3.2.3 on 2021-06-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
