# Generated by Django 3.2.3 on 2021-06-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default='story.svg', upload_to=''),
        ),
    ]
