# Generated by Django 3.2.3 on 2021-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='.'),
        ),
    ]
